// Generated by CoffeeScript 1.4.0
var app, port;

app = require('./.app');

port = app.port;

app.listen(port, function() {
  // console.log("now starting in environment: " + process.env);
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
